name: 'Open a Github Issue'
author: Alexandru Marinescu
description: 'Opens a Github Issue'
inputs:
  token:
    description: 'Github Token'
    required: true
  title:
    description: 'Issues Title'
    required: true
  body:
    description: 'Issue body'
  assignees:
    description: 'Issue Assignees'
outputs:
  issue:
    description: 'The issue object as a json string'
runs:
  using: node20
  main: dist/index.js
branding:
  icon: 'alert-circle'
  color: 'yellow'
